title: Algorithmic Foundations of Interactive Learning
description: Website for AFIL course.
theme: just-the-docs

url: https://interactive-learning-algos.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
